# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83aa0d778ee25e08262a80d1626541fda26ca16b0522442fdea36a92067bd01e1a917111fa2664e9e8f22e75f53dead633c54bf27863ea36fc751743226ee24d

test:
  secret_key_base: 5f680405b8ece04be8205bb4429237562cfe25083177ba614275a858e159166289caee55418eb7aae50d47cbbb1624f6a9b03b213b3825015940112bbb47d656

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
